"""
Большой набор предопределенных чистых цитат без имён, мест, цифр и ссылок.
"""

from typing import List, Dict, Optional

# Английские цитаты (чистые, без имён и ссылок)
EN_QUOTATIONS = [
    'The only way to do great work is to love what you do.',
    'Innovation distinguishes between a leader and a follower.',
    'Life is what happens to you while you are busy making other plans.',
    'The future belongs to those who believe in the beauty of their dreams.',
    'It is during our darkest moments that we must focus to see the light.',
    'Be yourself; everyone else is already taken.',
    'Two things are infinite: the universe and human stupidity.',
    'So many books, so little time.',
    'A room without books is like a body without a soul.',
    'You only live once, but if you do it right, once is enough.',
    'Be the change that you wish to see in the world.',
    'In three words I can sum up everything about life: it goes on.',
    'If you tell the truth, you do not have to remember anything.',
    'A friend is someone who knows all about you and still loves you.',
    'To live is the rarest thing in the world. Most people just exist.',
    'Without music, life would be a mistake.',
    'It is better to be hated for what you are than to be loved for what you are not.',
    'We accept the love we think we deserve.',
    'The person who has not pleasure in a good novel must be intolerably stupid.',
    'Imperfection is beauty, madness is genius and it is better to be absolutely ridiculous than absolutely boring.',
    'Success is not final, failure is not fatal.',
    'The only impossible journey is the one you never begin.',
    'In the middle of difficulty lies opportunity.',
    'The way to get started is to quit talking and begin doing.',
    'Do not let yesterday take up too much of today.',
    'You learn more from failure than from success.',
    'If you are working on something exciting, you do not have to be pushed.',
    'People who are crazy enough to think they can change the world are the ones who do.',
    'Failure will never overtake me if my determination to succeed is strong enough.',
    'Entrepreneurs are great at dealing with uncertainty and also very good at minimizing risk.',
    'The successful warrior is the average man with laser-like focus.',
    'Take up one idea. Make that one idea your life.',
    'I find that the harder I work, the more luck I seem to have.',
    'Do not be afraid to give up the good to go for the great.',
    'The journey of a thousand miles begins with one step.',
    'That which does not kill us makes us stronger.',
    'When the going gets tough, the tough get going.',
    'You must be the change you wish to see in the world.',
    'Twenty years from now you will be more disappointed by the things that you did not do than by the ones you did do.',
    'The difference between ordinary and extraordinary is that little extra.',
    'Great minds discuss ideas; average minds discuss events; small minds discuss people.',
    'A person who never made a mistake never tried anything new.',
    'Education is the most powerful weapon which you can use to change the world.',
    'The only person you are destined to become is the person you decide to be.',
    'Go confidently in the direction of your dreams. Live the life you have imagined.',
    'The two most important days in your life are the day you are born and the day you find out why.',
    'Whether you think you can or you think you cannot, you are right.',
    'People often say that motivation does not last. Well, neither does bathing. That is why we recommend it daily.',
    'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.',
    'The person who says it cannot be done should not interrupt the person who is doing it.',
    'Learn from yesterday, live for today, hope for tomorrow.',
    'You have to learn the rules of the game. And then you have to play better than anyone else.',
    'The future belongs to those who believe in the beauty of their dreams.',
    'Happiness is not something ready made. It comes from your own actions.',
    'The only thing we have to fear is fear itself.',
    'It does not matter how slowly you go as long as you do not stop.',
    'Everything you can imagine is real.',
    'Life is like riding a bicycle. To keep your balance, you must keep moving.',
    'Reality is merely an illusion, albeit a very persistent one.',
    'Nothing is impossible, the word itself says I am possible.',
    'The only limit to our realization of tomorrow will be our doubts of today.',
    'The way to get started is to quit talking and begin doing.',
    'Do what you can, with what you have, where you are.',
    'If you want to lift yourself up, lift up someone else.',
    'The best time to plant a tree was twenty years ago. The second best time is now.',
    'An unexamined life is not worth living.',
    'The only true wisdom is in knowing you know nothing.',
    'I cannot teach anybody anything. I can only make them think.',
    'The secret of getting ahead is getting started.',
    'Do not wait. The time will never be just right.',
    'Start where you are. Use what you have. Do what you can.',
    'The best revenge is massive success.',
    'For every minute you are angry you lose sixty seconds of happiness.',
    'A man who stands for nothing will fall for anything.',
    'What lies behind us and what lies before us are tiny matters compared to what lies within us.',
    'The only way out is through.',
    'You miss one hundred percent of the shots you do not take.',
    'The greatest glory in living lies not in never falling, but in rising every time we fall.',
    'The way to get started is to quit talking and begin doing.',
    'Life is what happens when you are busy making other plans.',
    'Spread love everywhere you go. Let no one ever come to you without leaving happier.',
    'When you reach the end of your rope, tie a knot in it and hang on.',
    'Always remember that you are absolutely unique. Just like everyone else.',
    'Do not judge each day by the harvest you reap but by the seeds that you plant.',
    'The future belongs to those who believe in the beauty of their dreams.',
    'Tell me and I forget. Teach me and I remember. Involve me and I learn.',
    'The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart.',
    'It is during our darkest moments that we must focus to see the light.',
    'Whoever is happy will make others happy too.',
    'Do not go where the path may lead, go instead where there is no path and leave a trail.',
    'You will face many defeats in life, but never let yourself be defeated.',
    'The greatest glory in living lies not in never falling, but in rising every time we fall.',
    'In the end, it is not the years in your life that count. It is the life in your years.',
    'Never let the fear of striking out keep you from playing the game.',
    'Life itself is the proper binge.',
    'Many of life failures are people who did not realize how close they were to success when they gave up.',
    'You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.',
    'Success usually comes to those who are too busy to be looking for it.',
    'If you want to live a happy life, tie it to a goal, not to people or things.',
    'Never let the fear of striking out keep you from playing the game.',
    'The only impossible journey is the one you never begin.',
    'In this life we cannot do great things. We can only do small things with great love.',
    'Only a life lived for others is a life worthwhile.',
    'The purpose of our lives is to be happy.',
    'Life is what happens to you while you are busy making other plans.',
    'You only live once, but if you do it right, once is enough.',
    'If you want to lift yourself up, lift up someone else.',
    'The only way to do great work is to love what you do.',
    'If life were predictable it would cease to be life, and be without flavor.',
    'In the end, it is not the years in your life that count. It is the life in your years.',
    'Life is a succession of lessons which must be lived to be understood.',
    'You will face many defeats in life, but never let yourself be defeated.',
    'Never let the fear of striking out keep you from playing the game.',
    'Life is never fair, and perhaps it is a good thing for most of us that it is not.',
    'The only impossible journey is the one you never begin.',
    'In this life we cannot do great things. We can only do small things with great love.',
    'Only a life lived for others is a life worthwhile.',
    'The purpose of our lives is to be happy.',
    'Get busy living or get busy dying.',
    'You have to learn the rules of the game. And then you have to play better than anyone else.',
    'The only limit to our realization of tomorrow will be our doubts of today.',
    'The way to get started is to quit talking and begin doing.',
    'Do what you can, with what you have, where you are.',
    'If you want to lift yourself up, lift up someone else.',
    'The best time to plant a tree was twenty years ago. The second best time is now.',
    'An unexamined life is not worth living.',
    'The only true wisdom is in knowing you know nothing.',
    'I cannot teach anybody anything. I can only make them think.',
    'The secret of getting ahead is getting started.',
    'Do not wait. The time will never be just right.',
    'Start where you are. Use what you have. Do what you can.',
    'The best revenge is massive success.',
    'For every minute you are angry you lose sixty seconds of happiness.',
    'A man who stands for nothing will fall for anything.',
    'What lies behind us and what lies before us are tiny matters compared to what lies within us.',
    'The only way out is through.',
    'You miss one hundred percent of the shots you do not take.',
    'The greatest glory in living lies not in never falling, but in rising every time we fall.',
    'The way to get started is to quit talking and begin doing.',
    'Life is what happens when you are busy making other plans.',
    'Spread love everywhere you go. Let no one ever come to you without leaving happier.',
    'When you reach the end of your rope, tie a knot in it and hang on.',
    'Always remember that you are absolutely unique. Just like everyone else.',
    'Do not judge each day by the harvest you reap but by the seeds that you plant.',
    'The future belongs to those who believe in the beauty of their dreams.',
    'Tell me and I forget. Teach me and I remember. Involve me and I learn.',
    'The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart.',
    'It is during our darkest moments that we must focus to see the light.',
    'Whoever is happy will make others happy too.',
    'Do not go where the path may lead, go instead where there is no path and leave a trail.',
    'You will face many defeats in life, but never let yourself be defeated.',
    'The greatest glory in living lies not in never falling, but in rising every time we fall.',
    'In the end, it is not the years in your life that count. It is the life in your years.',
    'Never let the fear of striking out keep you from playing the game.',
    'Life itself is the proper binge.',
    'Many of life failures are people who did not realize how close they were to success when they gave up.',
    'You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.',
    'Success usually comes to those who are too busy to be looking for it.',
    'If you want to live a happy life, tie it to a goal, not to people or things.',
    'Never let the fear of striking out keep you from playing the game.',
    'The only impossible journey is the one you never begin.',
    'In this life we cannot do great things. We can only do small things with great love.',
    'Only a life lived for others is a life worthwhile.',
    'The purpose of our lives is to be happy.',
    'Life is what happens to you while you are busy making other plans.',
    'You only live once, but if you do it right, once is enough.',
    'If you want to lift yourself up, lift up someone else.',
    'The only way to do great work is to love what you do.',
    'If life were predictable it would cease to be life, and be without flavor.',
    'In the end, it is not the years in your life that count. It is the life in your years.',
    'Life is a succession of lessons which must be lived to be understood.',
    'You will face many defeats in life, but never let yourself be defeated.',
    'Never let the fear of striking out keep you from playing the game.',
    'Life is never fair, and perhaps it is a good thing for most of us that it is not.',
    'The only impossible journey is the one you never begin.',
    'In this life we cannot do great things. We can only do small things with great love.',
    'Only a life lived for others is a life worthwhile.',
    'The purpose of our lives is to be happy.',
    'Get busy living or get busy dying.',
]

# Русские цитаты и пословицы (чистые, без имён и ссылок)
RU_QUOTATIONS = [
    'Век живи — век учись.',
    'Ученье — свет, а неученье — тьма.',
    'Терпение и труд всё перетрут.',
    'Без труда не вытащишь и рыбку из пруда.',
    'Что посеешь, то и пожнёшь.',
    'Семь раз отмерь — один раз отрежь.',
    'Тише едешь — дальше будешь.',
    'Не откладывай на завтра то, что можно сделать сегодня.',
    'Кто не работает, тот не ест.',
    'В гостях хорошо, а дома лучше.',
    'Лучше синица в руках, чем журавль в небе.',
    'Не всё то золото, что блестит.',
    'Дареному коню в зубы не смотрят.',
    'Любопытство — не порок, а большое безобразие.',
    'Слово — серебро, молчание — золото.',
    'В здоровом теле — здоровый дух.',
    'Повторение — мать учения.',
    'Знание — сила.',
    'Учиться никогда не поздно.',
    'Дорогу осилит идущий.',
    'Поспешишь — людей насмешишь.',
    'У страха глаза велики.',
    'Лучше поздно, чем никогда.',
    'Вода камень точит.',
    'Где тонко, там и рвётся.',
    'Семь бед — один ответ.',
    'Умный в гору не пойдёт, умный гору обойдёт.',
    'Кто ищет, тот всегда найдёт.',
    'Всякое дело мастера боится.',
    'Где родился, там и пригодился.',
    'Дело мастера боится.',
    'Капля камень точит.',
    'Один в поле не воин.',
    'Хорошее начало — половина дела.',
    'Цыплят по осени считают.',
    'Что написано пером, не вырубишь топором.',
    'Яблоко от яблони недалеко падает.',
    'Лучше один раз увидеть, чем сто раз услышать.',
    'Сколько волка ни корми, он всё в лес смотрит.',
    'Не в свои сани не садись.',
    'В тихом омуте черти водятся.',
    'После дождичка в четверг.',
    'Собака лает, ветер носит.',
    'Волков бояться — в лес не ходить.',
    'Всяк кулик своё болото хвалит.',
    'Где родился, там и сгодился.',
    'Дареному коню в зубы не смотрят.',
    'Два сапога пара.',
    'За двумя зайцами погонишься — ни одного не поймаешь.',
    'И волки сыты, и овцы целы.',
    'Как аукнется, так и откликнется.',
    'Копейка рубль бережёт.',
    'Куй железо, пока горячо.',
    'Лучше синица в руках, чем журавль в небе.',
    'Мал золотник, да дорог.',
    'На безрыбье и рак рыба.',
    'Не всё то золото, что блестит.',
    'Не имей сто рублей, а имей сто друзей.',
    'Один в поле не воин.',
    'Повторение — мать учения.',
    'Поспешишь — людей насмешишь.',
    'Семь раз отмерь — один раз отрежь.',
    'Слово — серебро, молчание — золото.',
    'Тише едешь — дальше будешь.',
    'У страха глаза велики.',
    'Ученье — свет, а неученье — тьма.',
    'Хорошее начало — половина дела.',
    'Цыплят по осени считают.',
    'Что написано пером, не вырубишь топором.',
    'Яблоко от яблони недалеко падает.',
    'Без труда не вытащишь и рыбку из пруда.',
    'В гостях хорошо, а дома лучше.',
    'В здоровом теле — здоровый дух.',
    'Век живи — век учись.',
    'Вода камень точит.',
    'Где тонко, там и рвётся.',
    'Дареному коню в зубах не смотрят.',
    'Дело мастера боится.',
    'Дорогу осилит идущий.',
    'Знание — сила.',
    'Капля камень точит.',
    'Кто ищет, тот всегда найдёт.',
    'Лучше поздно, чем никогда.',
    'Любопытство — не порок, а большое безобразие.',
    'Большое дело не сразу делается.',
    'Не откладывай на завтра то, что можно сделать сегодня.',
    'Один в поле не воин.',
    'Повторение — мать учения.',
    'Поспешишь — людей насмешишь.',
    'Семь бед — один ответ.',
    'Слово — серебро, молчание — золото.',
    'Терпение и труд всё перетрут.',
    'Тише едешь — дальше будешь.',
    'У страха глаза велики.',
    'Умный в гору не пойдёт, умный гору обойдёт.',
    'Учиться никогда не поздно.',
    'Ученье — свет, а неученье — тьма.',
    'Хорошее начало — половина дела.',
    'Что посеешь, то и пожнёшь.',
    'Яблоко от яблони недалеко падает.',
    'Без труда не вытащишь и рыбку из пруда.',
    'В гостях хорошо, а дома лучше.',
    'В здоровом теле — здоровый дух.',
    'Век живи — век учись.',
    'Вода камень точит.',
    'Где тонко, там и рвётся.',
    'Дареному коню в зубах не смотрят.',
    'Дело мастера боится.',
    'Дорогу осилит идущий.',
    'Знание — сила.',
    'Капля камень точит.',
    'Кто ищет, тот всегда найдёт.',
    'Лучше поздно, чем никогда.',
    'Любопытство — не порок, а большое безобразие.',
    'Большое дело не сразу делается.',
    'Не откладывай на завтра то, что можно сделать сегодня.',
    'Один в поле не воин.',
    'Повторение — мать учения.',
    'Поспешишь — людей насмешишь.',
    'Семь бед — один ответ.',
    'Слово — серебро, молчание — золото.',
    'Терпение и труд всё перетрут.',
    'Тише едешь — дальше будешь.',
    'У страха глаза велики.',
    'Умный в гору не пойдёт, умный гору обойдёт.',
    'Учиться никогда не поздно.',
    'Ученье — свет, а неученье — тьма.',
    'Хорошее начало — половина дела.',
    'Что посеешь, то и пожнёшь.',
    'Яблоко от яблони недалеко падает.',
    'Лучше один раз увидеть, чем сто раз услышать.',
    'Сколько волка ни корми, он всё в лес смотрит.',
    'Не в свои сани не садись.',
    'В тихом омуте черти водятся.',
    'После дождичка в четверг.',
    'Собака лает, ветер носит.',
    'Волков бояться — в лес не ходить.',
    'Всяк кулик своё болото хвалит.',
    'Где родился, там и сгодился.',
    'Дареному коню в зубы не смотрят.',
    'Два сапога пара.',
    'За двумя зайцами погонишься — ни одного не поймаешь.',
    'И волки сыты, и овцы целы.',
    'Как аукнется, так и откликнется.',
    'Копейка рубль бережёт.',
    'Куй железо, пока горячо.',
    'Лучше синица в руках, чем журавль в небе.',
    'Мал золотник, да дорог.',
    'На безрыбье и рак рыба.',
    'Не всё то золото, что блестит.',
    'Не имей сто рублей, а имей сто друзей.',
    'Один в поле не воин.',
    'Повторение — мать учения.',
    'Поспешишь — людей насмешишь.',
    'Семь раз отмерь — один раз отрежь.',
    'Слово — серебро, молчание — золото.',
    'Тише едешь — дальше будешь.',
    'У страха глаза велики.',
    'Ученье — свет, а неученье — тьма.',
    'Хорошее начало — половина дела.',
    'Цыплят по осени считают.',
    'Что написано пером, не вырубишь топором.',
    'Яблоко от яблони недалеко падает.',
]


def get_en_quotations() -> List[Dict[str, Optional[str]]]:
    """
    Получение английских цитат в формате для загрузчика.

    Returns:
        Список словарей с цитатами
    """
    return [
        {
            'text': quote,
            'language': 'en',
            'author': None,
            'source_url': None
        }
        for quote in EN_QUOTATIONS
    ]


def get_ru_quotations() -> List[Dict[str, Optional[str]]]:
    """
    Получение русских цитат в формате для загрузчика.

    Returns:
        Список словарей с цитатами
    """
    return [
        {
            'text': quote,
            'language': 'ru',
            'author': None,
            'source_url': None
        }
        for quote in RU_QUOTATIONS
    ]


def get_all_quotations() -> List[Dict[str, Optional[str]]]:
    """
    Получение всех цитат.

    Returns:
        Список словарей с цитатами
    """
    return get_en_quotations() + get_ru_quotations()
